package runner

import (
	"fmt"
	"html/template"
	"os"
)

const reportTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>qdesk · {{.TestName}}</title>
<style>
  :root { color-scheme: dark; }
  body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
         background:#0e0f12; color:#e7e9ef; margin:0; padding:24px; }
  header { max-width:1200px; margin:0 auto 24px; }
  h1 { font-size:24px; margin:0 0 8px; }
  .badge { display:inline-block; padding:4px 12px; border-radius:999px; font-weight:600; font-size:12px; letter-spacing:.4px; text-transform:uppercase; }
  .pass  { background:#0e3b1f; color:#7eef9c; }
  .fail  { background:#3b1010; color:#ff8b8b; }
  .error { background:#3b2810; color:#ffc97a; }
  .meta { color:#8a8f99; margin-top:8px; }
  main { max-width:1200px; margin:0 auto; }
  section { margin-top:32px; padding:16px 20px; background:#161821; border-radius:12px; }
  h2 { margin:0 0 12px; font-size:18px; }
  .step-head { display:flex; justify-content:space-between; align-items:center; gap:12px; }
  .turn { margin-top:14px; padding:14px; background:#1d2030; border-radius:10px; }
  .turn-meta { color:#8a8f99; font-size:12px; }
  .reasoning { margin-top:6px; }
  .action { font-family:ui-monospace, SFMono-Regular, Menlo, monospace;
            background:#0e0f12; padding:8px 10px; border-radius:6px; margin-top:6px; font-size:12px; overflow-x:auto; }
  img.shot { max-width:100%; max-height:400px; border:1px solid #2a2e3d; border-radius:8px; margin-top:8px; }
  .verify { display:flex; gap:16px; padding:14px; margin-top:12px; background:#1d2030; border-radius:10px; }
  .verify-text { flex:1; }
  .verify img { width:240px; height:auto; border:1px solid #2a2e3d; border-radius:8px; }
  .diag { white-space:pre-wrap; padding:14px; background:#0e0f12; border-left:4px solid #ffc97a; margin-top:14px; border-radius:6px; }
  code { background:#0e0f12; padding:1px 6px; border-radius:3px; font-size:12px; }
  footer { max-width:1200px; margin:24px auto; color:#5a606e; font-size:12px; }
</style>
</head>
<body>
<header>
  <h1>{{.TestName}}</h1>
  <span class="badge {{statusClass .Status}}">{{.Status}}</span>
  <div class="meta">
    <code>{{.TestPath}}</code>
    &middot; LLM: <code>{{.LLM}}</code>
    &middot; {{.StartedAt.Format "2006-01-02 15:04:05 UTC"}}
    &middot; duration {{duration .StartedAt .FinishedAt}}
  </div>
</header>

<main>

{{range .Steps}}
{{$step := .}}
<section>
  <div class="step-head">
    <h2>Step {{.Index}} · {{if .Done}}<span style="color:#7eef9c">✓</span>{{else}}<span style="color:#ff8b8b">✗</span>{{end}} {{.Goal}}</h2>
    <span class="turn-meta">{{len .Turns}} turn(s) &middot; {{duration .StartedAt .FinishedAt}}</span>
  </div>
  {{if .Failure}}<div class="diag" style="border-color:#ff8b8b">Failure: {{.Failure}}</div>{{end}}
  {{range $idx, $turn := .Turns}}
    <div class="turn">
      <div class="turn-meta">turn {{$idx}}{{if $turn.Done}} &middot; agent says DONE{{end}}</div>
      <div class="reasoning">{{$turn.Reasoning}}</div>
      {{if $turn.Action}}<pre class="action">{{actionJSON $turn.Action}}</pre>{{end}}
      {{if lt $idx (len $step.Screenshots)}}<img class="shot" src="{{index $step.Screenshots $idx}}" alt="screenshot">{{end}}
    </div>
  {{end}}
</section>
{{end}}

{{if .Verifies}}
<section>
  <h2>Expectations</h2>
  {{range .Verifies}}
    <div class="verify">
      <div class="verify-text">
        <div class="badge {{if .Passed}}pass{{else}}fail{{end}}">{{if .Passed}}PASS{{else}}FAIL{{end}}</div>
        <div style="margin-top:8px"><strong>{{.Expectation}}</strong></div>
        <div class="turn-meta" style="margin-top:6px">{{.Evidence}}</div>
      </div>
      {{if .Screenshot}}<img src="{{.Screenshot}}" alt="verify screenshot">{{end}}
    </div>
  {{end}}
</section>
{{end}}

{{if .Diagnosis}}
<section>
  <h2>AI diagnosis</h2>
  <div class="diag">{{.Diagnosis}}</div>
</section>
{{end}}

</main>
<footer>
  Generated by qdesk · <a href="trace.json" style="color:#7eef9c">trace.json</a>
</footer>
</body>
</html>`

// WriteReport renders an HTML report for the given trace into path.
func WriteReport(path string, t *Trace) error {
	funcs := template.FuncMap{
		"statusClass": func(s RunStatus) string {
			switch s {
			case StatusPass:
				return "pass"
			case StatusFail:
				return "fail"
			default:
				return "error"
			}
		},
		"duration": func(a, b interface{ String() string }) string {
			// best-effort: read times via type assertion in caller.
			return ""
		},
		"actionJSON": actionJSON,
	}
	// Replace the placeholder duration func with one that actually formats
	// time deltas — needs imports of time, so do it here.
	tmpl, err := template.New("report").Funcs(funcs).Funcs(template.FuncMap{
		"duration": durationFmt,
	}).Parse(reportTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, t)
}
